<?php

namespace Larawiz\Larawiz\Console;

use Larawiz\Larawiz\Larawiz;
use Illuminate\Filesystem\Filesystem;

class ClearBackupsCommand extends BaseLarawizCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'larawiz:clear-backups
                            {--force : Delete all backups without asking.}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Deletes all application backups generated by Larawiz.';

    /**
     * Filesystem implementation.
     *
     * @var \Illuminate\Filesystem\Filesystem
     */
    protected $filesystem;

    /**
     * Create a new command instance.
     *
     * @param  \Illuminate\Filesystem\Filesystem  $filesystem
     */
    public function __construct(Filesystem $filesystem)
    {
        parent::__construct();

        $this->filesystem = $filesystem;
    }

    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle()
    {
        parent::handle();

        if ($this->doesntHasBackups()) {
            return $this->line('There are no backups file, so nothing was deleted.');
        }

        if (! $this->option('force') && $this->doesntWantToDeleteBackups()) {
            return $this->line('No backups were deleted.');
        }

        $deleted = $this->deleteBackups();

        $this->line("A total of {$deleted} backups were deleted");
    }

    /**
     * Returns if there are no backups folders.
     *
     * @return bool
     */
    protected function doesntHasBackups()
    {
        $path = storage_path(Larawiz::BACKUPS_DIR);

        return $this->filesystem->missing($path) || empty($this->filesystem->directories($path));
    }

    /**
     * Returns if he doesn't want to delete all his backups.
     *
     * @return bool
     */
    protected function doesntWantToDeleteBackups()
    {
        return ! $this->confirm('Are you sure to delete ALL your project backups?');
    }

    /**
     * Delete the backups and returns the number of backups deleted.
     *
     * @return int
     */
    protected function deleteBackups()
    {
        $path = storage_path(Larawiz::BACKUPS_DIR);

        $directories = count($this->filesystem->directories($path));

        $this->filesystem->deleteDirectory($path, true);

        return $directories;
    }
}
